DROP TABLE IF EXISTS USERS;

CREATE TABLE IF NOT EXISTS USERS (
     id BIGINT AUTO_INCREMENT PRIMARY KEY,
     full_name VARCHAR(255) NOT NULL,
     username VARCHAR(255) UNIQUE NOT NULL,
     email VARCHAR(255) UNIQUE NOT NULL,
     password_hash VARCHAR(255) NOT NULL,
     registration_date TIMESTAMP NOT NULL
);